variable "openstack_user_domain_name" {}
variable "openstack_region" {}
variable "openstack_auth_url" {}
variable "openstack_project_name" {}
variable "openstack_project_username" {}
variable "openstack_project_password" {}
variable "network_name" {}
variable "subnet_name" {}
variable "network_cidr" {}
variable "network_provider" {}
variable "vlan_id" {}
variable "network_count" {}
variable "gateway" {}